[build]
  command = "npm run netlify:build"
  publish = "dist/public"
  functions = "netlify/functions"

# Environment variables
[build.environment]
  NODE_VERSION = "18"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# For Single Page Applications
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"